//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.03 at 05:09:04 PM IST 
//


package com.thang.demo.spring_boot_soap_example;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for user complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="user">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="empId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="salary" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "user", propOrder = {"tenChuThe","kieuThe", "soThe", "soCVC", "ngayHetHan",})
public class User {

    @XmlElement(required = true)
    protected String tenChuThe;
    protected String kieuThe;
    protected double soThe;
    protected double soCVC;
    protected int ngayHetHan;

    public String getTenChuThe() {
        return tenChuThe;
    }

    public void setTenChuThe(String tenChuThe) {
        this.tenChuThe = tenChuThe;
    }

    public String getKieuThe() {
        return kieuThe;
    }

    public void setKieuThe(String kieuThe) {
        this.kieuThe = kieuThe;
    }

    public double getSoThe() {
        return soThe;
    }

    public void setSoThe(double soThe) {
        this.soThe = soThe;
    }

    public double getSoCVC() {
        return soCVC;
    }

    public void setSoCVC(double soCVC) {
        this.soCVC = soCVC;
    }

    public int getNgayHetHan() {
        return ngayHetHan;
    }

    public void setNgayHetHan(int ngayHetHan) {
        this.ngayHetHan = ngayHetHan;
    }
}
